---
- name: Install Python for ubuntu
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes
  when: ansible_distribution == "ubuntu"

- name: Install Python for CentOS
  yum:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"

